dataset:

  image_root: "images/100k"

  train_images: "images/100k/train"
  val_images: "images/100k/val"
  test_images: "images/100k/test"

  train_labels: "labels/100k/train"
  val_labels: "labels/100k/val"
  test_labels: "labels/100k/test"

analysis:

  reports_dir: "outputs/reports"

  figures_dir: "outputs/figures"

processed:

  processed_dir: "outputs/processed"