dataset_root: "../datasets/bdd100k"

dataset:

  train_images: "images/100k/train"
  val_images: "images/100k/val"

  train_labels: "labels/100k/train"
  val_labels: "labels/100k/val"

analysis:

  reports_dir: "outputs/reports"
  figures_dir: "outputs/figures"

processed:

  processed_dir: "outputs/processed"